access_control:
  default_policy: one_factor
  rules:
    # Allow *arr calendar access
    - domain_regex: '^(movies|series|music|books)\..+$'
      policy: bypass
      resources: '^/feed(/v.)*/calendar/.+\.ics(\?.*)*$'
      methods:
        - GET
    # Allow *arr ping endpoint access
    - domain_regex: '^(movies|series|music|books|prowlarr)\..+$'
      policy: bypass
      resources: '^/ping$'
      methods:
        - HEAD
    # Allow qbittorrent healthcheck endpoint access
    - domain_regex: '^torrent\..+$'
      policy: bypass
      resources: '^/api/v2/app/version$'
      methods:
        - HEAD
    # Allow miniflux healthcheck endpoint access
    - domain_regex: '^miniflux\..+$'
      policy: bypass
      resources: '^/healthcheck$'
      methods:
        - HEAD
    # Allow homer on LAN
    - domain_regex: '^(home)\..+$'
      networks:
        - '192.168.0.0/24'
      methods:
        - GET
        - HEAD
      policy: bypass
    - domain_regex: '^(scrutiny|netdata)\..+$'
      policy: two_factor

notifier:
  disable_startup_check: false
  smtp:
    address: smtp://smtp.sendgrid.net:587
    timeout: 5s
    username: apikey
    sender: Authelia authelia@gauf.fr
    identifier: authelia
    subject: "[Authelia] {title}"
    disable_require_tls: false
    disable_html_emails: false
    tls:
      server_name: smtp.sendgrid.net
      skip_verify: false
      minimum_version: TLS1.2

authentication_backend:
  refresh_interval: 5m
  password_reset:
    disable: false
  ldap:
    implementation: lldap
    address: ldap://lldap:3890

session:
  expiration: 24h
  inactivity: 1M
  remember_me: 2M
  redis:
    host: authelia-valkey
    port: 6379

storage:
  postgres:
    address: tcp://authelia-db:5432
    database: authelia
    username: authelia

theme: auto
