access_control:
  default_policy: one_factor

notifier:
  disable_startup_check: false
  smtp:
    host: smtp.sendgrid.net
    port: 465
    timeout: 5s
    username: apikey
    identifier: authelia
    subject: "[Authelia] {title}"
    disable_require_tls: false
    disable_html_emails: false
    tls:
      server_name: smtp.sendgrid.net
      skip_verify: false
      minimum_version: TLS1.2

authentication_backend:
  disable_reset_password: true
  refresh_interval: 5m
  ldap:
    url: ldap://openldap
    username_attribute: uid
    additional_users_dn: ou=People
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectClass=groupOfNames))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName

session:
  name: authelia_session
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

storage:
  postgres:
    host: authelia-db
    database: authelia
    username: authelia
