access_control:
  default_policy: one_factor
  rules:
    # Allow *arr calendar access
    - domain_regex: '^(movies|series|music|books)\..+$'
      policy: bypass
      resources: '^/feed(/v.)*/calendar/.+\.ics(\?.*)*$'
      methods:
        - GET
    # Allow homer on LAN
    - domain_regex: '^(home)\..+$'
      networks:
        - '192.168.0.0/24'
      methods:
        - GET
        - HEAD
      policy: bypass
    - domain_regex: '^(scrutiny|netdata)\..+$'
      policy: two_factor

notifier:
  disable_startup_check: false
  smtp:
    host: smtp.sendgrid.net
    port: 587
    timeout: 5s
    username: apikey
    sender: Authelia authelia@gauf.fr
    identifier: authelia
    subject: "[Authelia] {title}"
    disable_require_tls: false
    disable_html_emails: false
    tls:
      server_name: smtp.sendgrid.net
      skip_verify: false
      minimum_version: TLS1.2

authentication_backend:
  refresh_interval: 5m
  ldap:
    url: ldap://openldap
    username_attribute: uid
    users_filter: (&({username_attribute}={input})(objectClass=inetOrgPerson))
    groups_filter: (&(member={dn})(objectClass=posixGroup))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName

session:
  expiration: 24h
  inactivity: 1M
  remember_me_duration: 2M
  redis:
    host: authelia-redis
    port: 6379

storage:
  postgres:
    host: authelia-db
    database: authelia
    username: authelia

theme: auto
