# yaml-language-server: $schema=https://www.authelia.com/schemas/latest/json-schema/configuration.json

access_control:
  default_policy: deny
  rules:
    # Allow *arr calendar access
    - domain_regex: '^(movies|series|music|books)\.{{ env "ROOT_DOMAIN" }}$'
      policy: bypass
      resources: '^/feed(/v.)*/calendar/.+\.ics(\?.*)*$'
      methods:
        - GET
    # Allow *arr ping endpoint access
    - domain_regex: '^(movies|series|music|books|prowlarr)\.{{ env "ROOT_DOMAIN" }}$'
      policy: bypass
      resources: "^/ping$"
      methods:
        - HEAD
    # Allow qbittorrent healthcheck endpoint access
    - domain_regex: '^torrent\.{{ env "ROOT_DOMAIN" }}$'
      policy: bypass
      resources: "^/api/v2/app/version$"
      methods:
        - HEAD
    # Allow miniflux healthcheck endpoint access
    - domain_regex: '^miniflux\.{{ env "ROOT_DOMAIN" }}$'
      policy: bypass
      resources: "^/healthcheck$"
      methods:
        - HEAD
    # Allow homer on LAN
    - domain_regex: '^home\.{{ env "ROOT_DOMAIN" }}$'
      networks:
        - "192.168.0.0/24"
      methods:
        - GET
        - HEAD
      policy: bypass
    # 2FA on admin apps
    - domain_regex: '^(scrutiny|grafana|prometheus)\.{{ env "ROOT_DOMAIN" }}$'
      domain: '{group}.{{ env "ROOT_DOMAIN" }}'
      policy: two_factor
    # Default rule for other apps
    - domain:
        - '{group}.{{ env "ROOT_DOMAIN" }}'
        - '{{ env "ROOT_DOMAIN" }}'
      policy: one_factor

notifier:
  disable_startup_check: false
  smtp:
    timeout: 5s
    identifier: authelia
    subject: "[Authelia] {title}"
    disable_require_tls: false
    disable_html_emails: false

authentication_backend:
  refresh_interval: 5m
  password_reset:
    disable: true
  password_change:
    disable: true
  ldap:
    implementation: lldap
    address: ldap://lldap:3890

session:
  expiration: 24h
  inactivity: 1M
  remember_me: 2M
  redis:
    host: authelia-valkey
    port: 6379

storage:
  postgres:
    address: tcp://authelia-db:5432
    database: authelia
    username: authelia

theme: auto

telemetry:
  metrics:
    enabled: true
