stages:
  - build
  - deploy

render-compose-graph:
  stage: build
  image:
    name: pmsipilot/docker-compose-viz
    entrypoint: [""]
  script:
    - mkdir public
    - /dcv/bin/entrypoint.sh render -m image docker-compose.yml --horizontal  --no-volumes  --force
  artifacts:
    paths:
      - docker-compose.png
    expire_in: 1 week

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  # requiring the environment of NodeJS 10
  image: node:10
  # add 'node_modules' to cache for speeding up builds
  cache:
    paths:
      - node_modules/ # Node modules and dependencies
  before_script:
    - npm install gitbook-cli -g # install gitbook
    - gitbook fetch 3.2.3 # fetch final stable version
    - gitbook install # add any requested plugins in book.json
  script:
    - gitbook build . public # build to public path
    - cp docker-compose.png public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    refs:
      - master
    changes:
      - README.md
      - .gitlab-ci.yml
