# THE MEDIA STACK #
# this docker-compose file will get a selection of media downloading/management webapps
# I've tried to simplify getting started as much as possible
#   1. configure your desired variables in the .env file
#   2. run `docker-compose up -d` from the folder with this docker-copose.yml folder
# NOTE this process is not fully automated and individual configuration of webapps is still required after docker compose
version: "2.4"

# basic common configuration for most containers
x-conf: &conf
  TZ: ${TZ}
  PGID: ${GID}
  PUID: ${UID}

# container restart policy
x-restart: &restart
  restart: always

# container logging policy
x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

# Traefik
x-traefik: &traefik
  traefik.enable: "true"

services:
  # reverse proxy
  traefik:
    image: traefik:v2.5
    user: ${UID}:${docker_group_id}
    cap_add:
      - NET_BIND_SERVICE
    command:
      - "--log.level=INFO"
      # docker configuration
      - "--providers.docker.network=traefik"
      - "--providers.docker.exposedbydefault=false"
      # entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certResolver=le"
      - "--entrypoints.websecure.http.middlewares=securityHeaders@file"
      # DNS challenge
      - "--certificatesresolvers.le=true"
      - "--certificatesresolvers.le.acme.storage=/traefik/acme.json"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.delayBeforeCheck=240"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=ovh"
      - "--certificatesresolvers.le.acme.email=${letsencrypt_email}"
      - "--certificatesresolvers.le.acme.keytype=EC384"
      - "--certificatesresolvers.le.acme.dnsChallenge.resolvers=1.1.1.1:53"
      # configs
      - "--providers.file.directory=/config/"
      # traefik API and dashboard
      - "--api=true"
      - "--api.dashboard=true"
      # traefik healthcheck
      - "--ping=true"
      - "--ping.manualrouting=true"
      # traefik access logs
      - "--accesslog=false"
    environment:
      OVH_ENDPOINT: ${OVH_ENDPOINT}
      OVH_APPLICATION_KEY: ${OVH_APPLICATION_KEY}
      OVH_APPLICATION_SECRET: ${OVH_APPLICATION_SECRET}
      OVH_CONSUMER_KEY: ${OVH_CONSUMER_KEY}
    labels:
      <<: *traefik
      traefik.http.routers.dashboard.rule: Host(`traefik.${root_domain}`)
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.middlewares: traefik-forward-auth
      traefik.http.routers.ping.rule: Host(`ping.${root_domain}`)
      traefik.http.routers.ping.service: ping@internal
    read_only: true
    volumes:
      - ${docker_data_folder}/traefik/logs:/var/log/traefik/
      - ${docker_data_folder}/traefik:/traefik
      - ./config/traefik:/config:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - "/tmp"
    networks:
      - traefik
      - kibana
      - calibre-web
      - homer
      - gollum
      - ghost
      - nextcloud-proxy
      - gotify
      - robots
      - netdata
      - lam
      - keycloak-proxy
    <<: *restart
    <<: *logging
    mem_limit: 200m
    cpus: "4"
    ports:
      - 80:80
      - 443:443

  # watchtower container to update images
  # NOTE to update the containers images' watchtower needs to restart the containers this implies some downtime when it does
  # NOTE watchtower also updates itself
  watchtower:
    image: containrrr/watchtower:latest
    <<: *restart
    <<: *logging
    mem_limit: 100m
    cpus: "1"
    read_only: true
    user: ${UID}:${docker_group_id}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      WATCHTOWER_NOTIFICATIONS: "gotify"
      WATCHTOWER_NOTIFICATION_GOTIFY_URL: "${WATCHTOWER_NOTIFICATION_GOTIFY_URL}"
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: "${WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN}"
    networks:
      - watchtower
    command:
      - "--cleanup"
      - "--schedule"
      - "0 0 5 * * *"

  # homer is a homepage container
  homer:
    hostname: ${root_domain}
    image: b4bz/homer:latest
    cpus: "1"
    mem_limit: 100m
    read_only: true
    <<: *restart
    <<: *logging
    environment:
      UID: ${UID}
      GID: ${GID}
    networks:
      - homer
    volumes:
      - ${docker_data_folder}/homer/config.yml:/www/assets/config.yml:ro
      - ${docker_data_folder}/homer/assets:/www/assets
    labels:
      <<: *traefik
      traefik.docker.network: homer
      traefik.http.routers.homer.rule: Host(`home.${root_domain}`, `${root_domain}`)
      # service
      traefik.http.services.homer.loadbalancer.server.port: "8080"
  samba:
    environment:
      SAMBA_LDAP_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      SID: ${SID}
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${docker_data_folder}/samba/nslcd.conf:/etc/nslcd.conf:ro
      - ${docker_data_folder}/samba/smb.conf:/etc/samba/smb.conf:ro
      - ${docker_data_folder}/samba/secrets.tdb:/var/lib/samba/private/secrets.tdb
      - /data/users:/data/users
    depends_on:
      - openldap
    <<: *restart
    <<: *logging
    mem_limit: 250m
    cpus: "2"
    networks:
      - samba
      - ldap
    image: guillaumedsde/samba-ldap

  ssh:
    ports:
      - "1998:2222"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${docker_data_folder}/samba/nslcd.conf:/etc/nslcd.conf:ro
      - ${docker_data_folder}/ssh/sshd_config:/etc/ssh/sshd_config:ro
      - ${docker_data_folder}/ssh/config:/config
      - /data/users:/data/users
    read_only: true
    tmpfs:
      - /run/sshd
      - /var:rw,exec
    environment:
      S6_READ_ONLY_ROOT: "1"
    depends_on:
      - openldap
    <<: *restart
    <<: *logging
    mem_limit: 100m
    cpus: "2"
    networks:
      - ssh
      - ldap
    image: guillaumedsde/ssh-ldap

  # Web Service Discovery host daemon
  # see https://github.com/christgau/wsdd
  wsdd:
    network_mode: host
    user: ${UID}:${GID}
    read_only: true
    mem_limit: 100M
    cpus: "1"
    <<: *restart
    <<: *logging
    command: --ipv4only --verbose --hostname ${WSDD_HOSTNAME} --interface ${WSDD_INTERFACE}
    image: guillaumedsde/wsdd:latest

  # Push notification service
  gotify:
    hostname: gotify.${root_domain}
    mem_limit: 100M
    cpus: "2"
    environment:
      <<: *conf
    <<: *restart
    <<: *logging
    labels:
      <<: *traefik
      traefik.docker.network: gotify
      traefik.http.routers.gotify.rule: Host(`gotify.${root_domain}`)
      # service
      traefik.http.services.gotify.loadbalancer.server.port: "80"
    volumes:
      - ${docker_data_folder}/gotify:/app/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gotify
    image: gotify/server:latest

  robots:
    image: nginx:alpine
    read_only: true
    mem_limit: 50M
    cpus: "1"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/robots.txt:/usr/share/nginx/html/robots.txt:ro
      - robots-nginx-cache:/var/cache/nginx
      - robots-nginx-pid:/var/run
      - robots-nginx-conf:/etc/nginx/conf.d/
    networks:
      - robots
    labels:
      <<: *traefik
      traefik.docker.network: robots
      traefik.http.routers.robots.rule: HostRegexp(`${root_domain}`,`{subhost:[a-z]+}.${root_domain}`) && Path(`/robots.txt`)
      # service
      traefik.http.services.robots.loadbalancer.server.port: "8080"

  ##################################################################
  # Monitoring

  # # netdata, server monitoring
  # netdata:
  #   hostname: status.${root_domain}
  #   image: netdata/netdata:latest
  #   <<: *restart
  #   <<: *logging
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ${docker_data_folder}/netdata/health_alarm_notify.conf:/etc/netdata/health_alarm_notify.conf
  #   networks:
  #     - netdata
  #   environment:
  #     <<: *conf
  #     PGID: ${docker_group_id}
  #   labels:
  #     <<: *traefik
  #     traefik.docker.network: netdata
  #     traefik.http.routers.netdata.rule: Host(`status.${root_domain}`)
  #     # service
  #     traefik.http.services.netdata.loadbalancer.server.port: "19999"
  #     # Forward auth
  #     traefik.http.routers.netdata.middlewares: keycloak-forward-auth
  #   cap_add:
  #     - SYS_PTRACE
  #   security_opt:
  #     - apparmor:unconfined
  #   mem_limit: 500m
  #   cpus: "2"

  ##################################################################
  # Authentication

  # LDAP server
  openldap:
    hostname: ldap.${old_root_domain}
    image: osixia/openldap:1.5.0
    mem_limit: 500m
    environment:
      HOSTNAME: ldap.${old_root_domain}
      LDAP_DOMAIN: ${old_root_domain}
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: ldap.${old_root_domain}.cer
      LDAP_TLS_KEY_FILENAME: ldap.${old_root_domain}.key
      LDAP_TLS_CA_CRT_FILENAME: ca.cer
      LDAP_OPENLDAP_UID: ${UID}
      LDAP_OPENLDAP_GID: ${GID}
    command: "--copy-service --loglevel debug"
    <<: *restart
    <<: *logging
    networks:
      - ldap
    ports:
      - 389:389
      - 636:636
    volumes:
      - ${docker_data_folder}/openldap/ldap:/var/lib/ldap
      - ${docker_data_folder}/openldap/slapd.d:/etc/ldap/slapd.d
      # ubuntu path for Samba LDIF, this might be different with other distributions
      - ./ldap_templates/samba/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/samba.ldif:ro
      # gotten from https://ubuntu.com/server/docs/samba-openldap-backend
      - ./ldap_templates/samba_indices.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/samba_indices.ldif:ro
      - ./ldap_templates/memberof.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/memberof.ldif:ro
      # certificates
      - ${docker_data_folder}/openldap/certs/ldap.${old_root_domain}:/container/service/slapd/assets/certs:ro

  # LDAP Server management web GUI
  lam:
    image: ldapaccountmanager/lam:stable
    volumes:
      - ${docker_data_folder}/lam/config.cfg:/etc/ldap-account-manager/config.cfg
      - ${docker_data_folder}/lam/lam.conf:/var/lib/ldap-account-manager/config/lam.conf
    environment:
      LAM_SKIP_PRECONFIGURE: "true"
    networks:
      - lam
      - ldap
    depends_on:
      - openldap
    <<: *restart
    <<: *logging
    mem_limit: 100m
    labels:
      <<: *traefik
      traefik.docker.network: lam
      traefik.http.routers.lam.rule: Host(`lam.${root_domain}`)
      # service
      traefik.http.services.lam.loadbalancer.server.port: "80"
      # Forward auth
      traefik.http.routers.lam.middlewares: traefik-forward-auth

  # SSO
  keycloak:
    image: jboss/keycloak:latest
    environment:
      # Technically, this could be auto-detected, but we prefer to be prescriptive
      DB_VENDOR: postgres
      DB_DATABASE: keycloak
      DB_ADDR: keycloak-db
      DB_USER: keycloak
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      # This is required to run keycloak behind traefik
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_HOSTNAME: keycloak.${root_domain}
    <<: *restart
    <<: *logging
    mem_limit: 750m
    depends_on:
      - keycloak-db
      - openldap
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - keycloak-proxy
      - ldap
      - keycloak
    labels:
      <<: *traefik
      traefik.docker.network: keycloak-proxy
      traefik.http.routers.keycloak.rule: Host(`keycloak.${root_domain}`)
      # service
      traefik.http.services.keycloak.loadbalancer.server.port: "8080"

  # DB for keycloak
  keycloak-db:
    <<: *restart
    <<: *logging
    mem_limit: 250m
    environment:
      # Tell Postgress what user/password to create
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    image: postgres:12-alpine
    volumes:
      - ${docker_data_folder}/keycloak-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - keycloak

  authelia:
    image: authelia/authelia:4.33
    environment:
      AUTHELIA_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
      AUTHELIA_DB_PASSWORD: ${AUTHELIA_DB_PASSWORD}
      AUTHELIA_DB_ENCRYPTION_KEY: ${AUTHELIA_DB_ENCRYPTION_KEY}
      root_domain: ${root_domain}
      AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ADMIN_USER: ${LDAP_ADMIN_USER}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      AUTHELIA_CHECK_EMAIL: ${letsencrypt_email}
      SENDGRID_PASS: ${SENDGRID_PASS}
    command:
      - --config
      - /config/config.yml
    <<: *restart
    <<: *logging
    mem_limit: 500m
    depends_on:
      - authelia-db
      - openldap
    volumes:
      - ./config/authelia:/config:ro
    networks:
      - authelia-proxy
      - ldap
      - authelia
    labels:
      <<: *traefik
      traefik.docker.network: authelia-proxy
      traefik.http.routers.authelia.rule: Host(`authelia.${root_domain}`)
      # service
      traefik.http.services.authelia.loadbalancer.server.port: "9091"

  # DB for authelia
  authelia-db:
    <<: *restart
    <<: *logging
    mem_limit: 250m
    environment:
      POSTGRES_USER: authelia
      POSTGRES_PASSWORD: ${AUTHELIA_DB_PASSWORD}
    image: postgres:14-alpine
    volumes:
      - ${docker_data_folder}/authelia-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - authelia

  # OIDC forward authentication for traefik
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    <<: *restart
    <<: *logging
    mem_limit: 100m
    environment:
      PROVIDERS_GOOGLE_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      PROVIDERS_GOOGLE_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      #OIDC_ISSUER: https://accounts.google.com
      WHITELIST: "${allowed_emails}"
      AUTH_HOST: "oauth.${root_domain}"
      COOKIE_DOMAIN: "${root_domain}"
      COOKIE_NAME: _google_forward_auth
      CSRF_COOKIE_NAME: _google_forward_auth_csrf
    networks:
      - traefik
    labels:
      <<: *traefik
      # HTTP entrypoint
      traefik.http.routers.traefik-forward-auth.rule: Host(`oauth.${root_domain}`)
      # service
      traefik.http.services.traefik-forward-auth.loadbalancer.server.port: "4181"
      # Forward auth
      traefik.http.middlewares.traefik-forward-auth.forwardauth.address: http://traefik-forward-auth:4181
      traefik.http.routers.traefik-forward-auth.middlewares: traefik-forward-auth
      traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders: X-Forwarded-User

networks:
  watchtower:
    driver: bridge
    name: watchtower
  traefik:
    driver: bridge
    name: traefik
  ldap:
    driver: bridge
    internal: true
    name: ldap
  keycloak:
    driver: bridge
    internal: true
    name: keycloak
  authelia:
    driver: bridge
    internal: true
    name: authelia
  nextcloud:
    driver: bridge
    internal: true
    name: nextcloud
  samba:
    driver: bridge
    name: samba
  ssh:
    driver: bridge
    name: ssh
  kibana:
    driver: bridge
    internal: true
    name: kibana
  calibre-web:
    driver: bridge
    name: calibre-web
  homer:
    driver: bridge
    internal: true
    name: homer
  gollum:
    driver: bridge
    internal: true
    name: gollum
  ghost:
    driver: bridge
    name: ghost
  nextcloud-proxy:
    driver: bridge
    name: nextcloud-proxy
  gotify:
    driver: bridge
    internal: true
    name: gotify
  robots:
    driver: bridge
    internal: true
    name: robots
  netdata:
    driver: bridge
    internal: true
    name: netdata
  lam:
    driver: bridge
    internal: true
    name: lam
  keycloak-proxy:
    driver: bridge
    name: keycloak-proxy
  authelia-proxy:
    driver: bridge
    name: authelia-proxy


volumes:
  robots-nginx-cache:
  robots-nginx-pid:
  robots-nginx-conf:
  torrent-blackhole:
