http:
  middlewares:
    securityHeaders:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        sslRedirect: true
        stsPreload: true
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        featurePolicy: "camera 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none'; payment 'none'; speaker 'none'; usb 'none'; vibrate 'none'; vr 'none';"
        referrerPolicy: "no-referrer"
        # contentSecurityPolicy: "default-src 'self'"
        customResponseHeaders:
          Server: ""
          X-Powered-By: ""
          X-Robots-Tag: "none"
          Permissions-Policy: "camera 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none'; payment 'none'; speaker 'none'; usb 'none'; vibrate 'none'; vr 'none';"
