http:
  middlewares:
    securityHeaders:
      headers:
        # frameDeny: true
        customFrameOptionsValue: SAMEORIGIN
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        sslRedirect: true
        stsPreload: true
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        featurePolicy: "camera 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none'; payment 'none'; speaker 'none'; usb 'none'; vibrate 'none'; vr 'none';"
        referrerPolicy: "no-referrer"
        # contentSecurityPolicy: "default-src 'self'"
        customResponseHeaders:
          Server: ""
          X-Powered-By: ""
          X-Robots-Tag: "none"
          Permissions-Policy: "accelerometer=(), ambient-light-sensor=(), autoplay=(), camera=(), display-capture=(), document-domain=(), document-write=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), speaker=(), sync-xhr=(), usb=(), wake-lock=(), vr=(), xr=(), interest-cohort=()"
