http:
  middlewares:
    securityHeaders:
      headers:
        customFrameOptionsValue: SAMEORIGIN
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        sslRedirect: true
        stsPreload: true
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        featurePolicy: "camera 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none'; payment 'none'; speaker 'none'; usb 'none'; vibrate 'none'; vr 'none';"
        referrerPolicy: "strict-origin-when-cross-origin"
        customResponseHeaders:
          Server: ""
          X-Powered-By: ""
          X-Robots-Tag: "none"
