http:
  middlewares:
    securityHeaders:
      # NOTE: all headers are case insensitive
      headers:
        customResponseHeaders:
          x-robots-tag: 'noindex, nofollow'
          x-frame-options: 'SAMEORIGIN'
          permissions-policy: 'interest-cohort=()'
          referrer-policy: 'strict-origin-when-cross-origin'
          x-content-type-options: 'nosniff'
          strict-transport-security: 'max-age=63072000; includeSubDomains; preload'
          server:
          x-powered-by:
          x-aspnet-version:
          x-aspnetmvc-version:
        customRequestHeaders:
          x-remote-user:
          remote-user: