http:
  middlewares:
    securityHeaders:
      # NOTE: all headers are case insensitive
      # NOTE: set to empty string to remove header (yaml null value does not work)
      headers:
        customResponseHeaders:
          x-robots-tag: 'noindex, nofollow'
          x-frame-options: 'SAMEORIGIN'
          permissions-policy: 'interest-cohort=()'
          referrer-policy: 'strict-origin-when-cross-origin'
          x-content-type-options: 'nosniff'
          strict-transport-security: 'max-age=63072000; includeSubDomains; preload'
          server: ""
          x-powered-by: ""
          x-aspnet-version: ""
          x-aspnetmvc-version: ""
        customRequestHeaders:
          remote-user: ""
          remote_user: ""
          # NOTE: remove all variants of remote user, see:
          #       https://github.com/benoitc/gunicorn/issues/2799
          x-remote-user: ""
          x_remote_user: ""
          x-remote_user: ""
          x_remote-user: ""