---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "${root_domain}"
subtitle: "hosted on ${root_domain}"
# logo: "assets/homer.png"
# Alternatively a fa icon can be provided:
icon: "fas fa-skull-crossbones"
# footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>'  # set false if you want to hide it.header:
footer: false

# Optional message
# message:
#   # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
#   style: "is-warning"
#   title: "Optional message!"
#   content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque risus mi, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum felis venenatis efficitur. Aenean ac eleifend lacus, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  # - name: "ansible"
  #   icon: "fab fa-github"
  #   url: "https://github.com/xxxxx/ansible/"
  #   target: '_blank' # optional html a tag target attribute
  - name: "Source Code"
    icon: "fas fa-code"
    url: "https://gitlab.com/guillaumedsde/docker-media-stack"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Consume media"
    icon: "fas fa-photo-video"
    items:
      # - name: "Jenkins"
      #   logo: "/assets/tools/jenkins.png"
      #   # Alternatively a fa icon can be provided:
      #   # icon: "fab fa-jenkins"
      #   subtitle: "Continuous integration server"
      #   tag: "CI"
      #   url: "#"
      #   target: '_blank' # optional html a tag target attribute
      # - name: "RabbitMQ Management"
      #   logo: "/assets/tools/rabbitmq.png"
      #   subtitle: "Manage & monitor RabbitMQ server"
      #   tag: "haproxy"
      #   # Optional tagstyle
      #   tagstyle: "is-success"
      #   url: "#"
      - name: "Plex"
        # icon: "fas fa-tv"
        logo: "/assets/plex.png"
        subtitle: "consume Movies, Music, TV Shows and Pictures"
        tag: "consume"
        url: "https://plex.${root_domain}"
      - name: "Calibre"
        logo: "/assets/calibreweb.png"
        subtitle: "Read books"
        tag: "consume"
        url: "https://read.${root_domain}"
  - name: "Add Media"
    icon: "fas fa-plus-square"
    items:
      - name: "Ombi"
        logo: "/assets/ombi.png"
        subtitle: "Easily add Movies, TV Shows and Music"
        tag: "add"
        url: "https://ombi.${root_domain}"
      - name: "Lazy Librarian"
        logo: "/assets/lazylibrarian.png"
        subtitle: "Add Books"
        tag: "add"
        url: "https://books.${root_domain}"
      - name: "Radarr"
        logo: "/assets/radarr.png"
        subtitle: "Add Movies"
        tag: "add"
        url: "https://movies.${root_domain}"
      - name: "Sonarr"
        logo: "/assets/sonarr.png"
        subtitle: "Add TV Shows"
        tag: "add"
        url: "https://series.${root_domain}"
      - name: "Lidarr"
        logo: "/assets/lidarr.png"
        subtitle: "Add Music"
        tag: "add"
        url: "https://music.${root_domain}"
      - name: "Bazaar"
        logo: "/assets/bazarr.png"
        subtitle: "Add Subtitles"
        tag: "add"
        url: "https://subtitles.${root_domain}"
  - name: "Blogs"
    icon: "fas fa-blog"
    items:
      - name: "Etienne"
        icon: "fas fa-blog"
        subtitle: "Photo Blog"
        tag: "blog"
        url: "http://etienne.desusanne.com"
      - name: "Margot"
        icon: "fas fa-blog"
        subtitle: "Portfolio"
        tag: "blog"
        url: "http://margot.desusanne.com"
      - name: "Guillaume"
        icon: "fas fa-blog"
        subtitle: "Blog"
        tag: "blog"
        url: "http://blog.guillaume.desusanne.com"
  - name: "Download"
    icon: "fas fa-download"
    items:
      - name: "qBittorrent"
        logo: "/assets/qbittorrent.svg"
        subtitle: "Download Torrents"
        tag: "download"
        url: "https://torrent.${root_domain}"
      - name: "Hydra"
        logo: "/assets/nzbhydra.png"
        subtitle: "Search for Torrents"
        tag: "download"
        url: "https://hydra.${root_domain}"
      - name: "Jackett"
        logo: "/assets/jackett.png"
        subtitle: "Search for Torrents (Prefer Hydra)"
        tag: "download"
        url: "https://jackett.${root_domain}"
      - name: "Pyload"
        logo: "/assets/pyload.png"
        subtitle: "Download files"
        tag: "download"
        url: "https://download.${root_domain}"
      - name: "Youtube-dl"
        logo: "/assets/youtubedl.png"
        subtitle: "Download videos"
        tag: "download"
        url: "https://yt-dl.${root_domain}/youtube-dl"
  - name: "Tools"
    icon: "fas fa-tools"
    items:
      - name: "Gollum"
        icon: "fas fa-tools"
        subtitle: "Documentation"
        tag: "tools"
        url: "https://docs.${root_domain}"
      - name: "Unmanic"
        icon: "fas fa-tools"
        subtitle: "Transcode video files"
        tag: "tools"
        url: "https://transcode.${root_domain}"
  - name: "Monitoring"
    icon: "fas fa-chart-bar"
    items:
      - name: "Netdata"
        logo: "/assets/netdata.png"
        subtitle: "Monitor Server"
        tag: "monitor"
        url: "https://status.${root_domain}"
      - name: "Tautulli"
        logo: "/assets/tautulli.png"
        subtitle: "Monitor Plex Server"
        tag: "monitor"
        url: "https://tautulli.${root_domain}"
  - name: "Authentication"
    icon: "fas fa-users"
    items:
      - name: "LAM"
        icon: "fas fa-chart-bar"
        subtitle: "Manage LDAP users"
        tag: "auth"
        url: "https://lam.${root_domain}"
      - name: "Keycloak"
        logo: "/assets/keycloak.svg"
        subtitle: "Manage SSO"
        tag: "auth"
        url: "https://keycloak.${root_domain}"
