filebeat.config.modules:
  enabled: true
  path: ${path.config}/modules.d/*.yml

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

logging.to_files: false

setup:
  kibana.host: "kibana:5601"
  dashboards.enabled: true
