source: syslog
listen_addr: 0.0.0.0
listen_port: 4242
labels:
  type: traefik
---
source: syslog
listen_addr: 0.0.0.0
listen_port: 4243
labels:
  type: authelia
---
source: file
filenames:
  - /var/log/nextcloud.log
labels:
  type: nextcloud
