---
source: docker
docker_host: tcp://docker-socket-proxy:2375
container_name:
  - traefik
labels:
  type: traefik
---
source: docker
docker_host: tcp://docker-socket-proxy:2375
container_name:
  - authelia
labels:
  type: authelia
---
source: file
filenames:
  - /var/log/nextcloud.log
labels:
  type: nextcloud
---
source: docker
docker_host: tcp://docker-socket-proxy:2375
container_name:
  - jellyfin
labels:
  type: jellyfin
