name: ip_remediation
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip"

decisions:
  - type: ban
    # NOTE: Ban 7 days
    duration: 168h

notifications:
  - discord

on_success: break